name: Release Builds
on: push
env:
  LLVM_VERSION: "23.1.2"
  QT_VERSION: "6.12.0"
  LIBSBML_VERSION: "v5.21.2"
  LIBEXPAT_VERSION: "R_2_8_5"
  SYMENGINE_VERSION: "v0.15.0"
  GMP_VERSION: "6.3.0"
  MPFR_VERSION: "4.2.2"
  MPIR_MSVC_VERSION: "f84ce09218b91d4c4fdf26e75093918c9fdb7046"
  MPFR_MSVC_VERSION: "f32587226978185abf3df725edbd79da985c7e8c"
  SPDLOG_VERSION: "v1.17.0"
  LIBTIFF_VERSION: "v4.7.2"
  FMT_VERSION: "12.2.0"
  TBB_VERSION: "v2023.1.0"
  DPL_VERSION: "oneDPL-release-2022.13.0"
  OPENCV_VERSION: "5.0.0"
  CATCH2_VERSION: "v3.16.0"
  BENCHMARK_VERSION: "v1.9.5"
  CGAL_VERSION: "v6.2.1"
  BOOST_VERSION: "1.92.0"
  QCUSTOMPLOT_VERSION: "2.1.1"
  CEREAL_VERSION: "v1.3.2"
  PAGMO_VERSION: "v2.20.0"
  BZIP2_VERSION: "bzip2-1.0.8"
  ZIPPER_VERSION: "master"
  COMBINE_VERSION: "master"
  FUNCTION2_VERSION: "4.2.5"
  VTK_VERSION: "v9.7.1"
  SCOTCH_VERSION: "v7.0.16"
  NLOPT_VERSION: "v2.11.0"
  CUDA_REDIST_VERSION: "13.4.92"
  METALCPP_VERSION: "macOS26.4_iOS26.4"
concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: "ubuntu-22.04"
          - os: "ubuntu-22.04"
            BUILD_TAG: "_tsan"
          - os: "ubuntu-22.04-arm"
          - os: "macos-26"
          - os: "windows-2022"
          - os: "windows-11-arm"
    env:
      BUILD_TAG: ${{ matrix.BUILD_TAG }}
    steps:
      - uses: spatial-model-editor/setup-ci@2026.10.02
        with:
          sme_deps_llvm: ${{ env.LLVM_VERSION }}
          sme_deps_qt: ${{ env.QT_VERSION }}
          build_tag: ${{ matrix.BUILD_TAG }}
          cache_id: ${{ matrix.BUILD_TAG }}
      - uses: actions/checkout@v7
      - name: Build script
        if: runner.os != 'Windows'
        run: ./build.sh
      - name: Build script
        if: runner.os == 'Windows'
        run: ./build.ps1
      - uses: actions/upload-artifact@v7
        with:
          name: artifacts-${{ matrix.os }}${{ matrix.BUILD_TAG }}
          path: ./artefacts/*
          retention-days: 3
  release:
    name: Upload Binaries to GitHub Release
    needs: [build]
    runs-on: ubuntu-latest
    # upload binaries to github release if commit is tagged
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          repo: spatial-model-editor/sme_deps_common
          keep_latest: 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v8
        with:
          pattern: artifacts-*
          merge-multiple: true
          path: binaries
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: binaries/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
